### ISSUE TITLE
IOS ‘Share With’ icon no longer available

### ISSUE THREAD

**Issue by arnie62** [rob-miller/rTracker#7]
The ios ‘share with’ icon has disappeared from display, unable to export data.

IOS 14.4

Many Thanks

**Comment by rob-miller** [comment]
Thank you, what device is this on?  I'm not yet able to replicate.  I assume you've tried killing and restarting the app?

**Comment by arnie62** [comment]
Hi Rob

Device is an ipad 6th generation. Although I have now replicated the scenario on my iphone SE2, both are on IOS 14.4.

When I open a tracker, I see ‘export’ -this may have replaced the ios share with dialogue at some point? (its been a while since I have backed my trackers up so I cant remember) However, when I select export, the dialogue for ‘save as csv ‘etc does not open. Instead it is saved straight to the app. Screen shots attached:

![9AED006D-5C4F-437D-87BF-60141EF5992F](https://user-images.githubusercontent.com/57703307/109384995-7ecc5c00-78e8-11eb-9b0e-b02f90dca283.png)
![BCE7CBCB-0CDB-4F3E-B12F-8BE5B679F16B](https://user-images.githubusercontent.com/57703307/109384999-83911000-78e8-11eb-85f5-f5cb4095e6c2.png)

**Comment by rob-miller** [comment]
Thank you for the follow-up Arnie.  I can replicate it in the simulator now, it is indeed device dependent so no doubt a recent deprecation that I can investigate.  As the dialogue says, the csv and plist files are exported to the device folders for the app (iTunes or Finder on the Mac are the current methods I think).  Nonetheless I need the other functionality in the changed menu as well so will work on a new release.

**Comment by arnie62** [comment]
Thanks, much appreciated Rob.

**Comment by rob-miller** [comment]
Hi Arnie,
The decision point for displaying the icon with menu vs. the 'Export' button is whether or not the app can send mail.  Turns out there was a bug in the simulator that some simulated devices thought they could send mail, so I actually don't have anything to replicate on.  
So please go into your device settings and check things like having email accounts configured and default mail app set?  There's a known bug that iOS ignores your default Mail app for this, but on mine having something else configured (gmail) does not keep the icon from showing.
thanks

**Comment by arnie62** [comment]
Hi Rob. Added an additional email account as suggested and the icon and associated menu are now showing. Many thanks for your help. Great app.
Arnie

13 Apr 2021, 15:56 by ***@***.***:

**Comment by rob-miller** [comment]
Version 3.30 provides various updates for iOS 14.4, including change so menu icon always displayed.  Email entries not shown if mail not configured, but others are.
